FROM python:3.10

# Set working dir
WORKDIR /app

# Copy code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir fastapi uvicorn tensorflow pandas numpy

# Expose API port
EXPOSE 8000

# Run the FastAPI server
CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000"]