language = "python"
providers=["python"]

[start]
cmd="uvicorn serve:app --host 0.0.0.0 --port 8000"

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]
